name = "redirect"
type = "webpack"

account_id = "ACCOUNT_ID_HERE"
workers_dev = true
route = ""
zone_id = ""

kv_namespaces = [ 
    { binding = "SHORTEN", preview_id = "PREVIEW_ID_HERE" }
]

[site]
bucket = "./public"
entry-point = "workers-site"

[env.production]
workers_dev = true
kv_namespaces = [
    { binding = "SHORTEN", id = "ID_HERE", preview_id = "PREVIEW_ID_HERE" }
]
